trigger:
- main

pool:
  vmImage: ubuntu-22.04

variables:
  buildFolder: dist  # Change this if your build outputs to something else like build or out

steps:
- script: echo "👋 Hello from the pipeline!"
  displayName: 'Say Hello'

# Install dependencies
- script: npm install
  displayName: 'Install dependencies'

# Optional: Relax TypeScript strict rules
- script: |
    echo "🔧 Relaxing TypeScript strict rules"
    for file in tsconfig.json tsconfig.app.json tsconfig.node.json; do
      if [ -f "$file" ]; then
        echo "Patching $file"
        sed -i 's/"noUnusedLocals": true/"noUnusedLocals": false/g' "$file" || true
        sed -i 's/"noUnusedParameters": true/"noUnusedParameters": false/g' "$file" || true
        grep -q '"noUnusedLocals"' "$file" || sed -i '/"compilerOptions": {/a \    "noUnusedLocals": false,' "$file"
        grep -q '"noUnusedParameters"' "$file" || sed -i '/"compilerOptions": {/a \    "noUnusedParameters": false,' "$file"
      fi
    done
  displayName: 'Disable TS Unused Checks'

# Build the project
- script: npm run build
  displayName: 'Build project'

# Deploy to Netlify via CLI
- script: |
    npm install -g netlify-cli
    echo "🚀 Deploying to Netlify..."
    netlify deploy --prod --dir=$(buildFolder) --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID
  displayName: 'Deploy to Netlify'
  env:
    NETLIFY_AUTH_TOKEN: $(NETLIFY_AUTH_TOKEN)
    NETLIFY_SITE_ID: $(NETLIFY_SITE_ID)
