# Starter pipeline
trigger:
- main

pool:
  vmImage: ubuntu-22.04

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# Install dependencies
- script: npm install
  displayName: 'Install dependencies'

# Relax TypeScript rules (no jq, works with any tsconfig)
- script: |
    echo "Patching tsconfig.json to disable strict unused checks..."
    node -e "let fs=require('fs');let f='tsconfig.json';let j=JSON.parse(fs.readFileSync(f));j.compilerOptions=j.compilerOptions||{};j.compilerOptions.noUnusedLocals=false;j.compilerOptions.noUnusedParameters=false;fs.writeFileSync(f,JSON.stringify(j,null,2));"
  displayName: 'Relax TypeScript rules'

# Build the project
- script: npm run build
  displayName: 'Build project'

# Deploy to Netlify
- script: |
    npm install -g netlify-cli
    netlify deploy --dir=dist --prod --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID
  displayName: 'Deploy to Netlify'
  env:
    NETLIFY_AUTH_TOKEN: $(NETLIFY_AUTH_TOKEN)
    NETLIFY_SITE_ID: $(NETLIFY_SITE_ID)
