# Starter pipeline
trigger:
- main

pool:
  vmImage: ubuntu-22.04

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# Install dependencies
- script: npm install
  displayName: 'Install dependencies'

# Patch tsconfig.json to allow unused variables (simple shell method)
- script: |
    echo "Patching tsconfig.json to disable noUnusedLocals and noUnusedParameters..."
    sed -i 's/"noUnusedLocals": true/"noUnusedLocals": false/' tsconfig.json || echo '"noUnusedLocals": false' >> tsconfig.json
    sed -i 's/"noUnusedParameters": true/"noUnusedParameters": false/' tsconfig.json || echo '"noUnusedParameters": false' >> tsconfig.json
  displayName: 'Relax TypeScript build rules'
  condition: succeeded()

# Build the project
- script: npm run build
  displayName: 'Build project'

# Deploy to Netlify
- script: |
    npm install -g netlify-cli
    netlify deploy --dir=dist --prod --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID
  displayName: 'Deploy to Netlify'
  env:
    NETLIFY_AUTH_TOKEN: $(NETLIFY_AUTH_TOKEN)
    NETLIFY_SITE_ID: $(NETLIFY_SITE_ID)
