trigger:
- main

pool:
  vmImage: ubuntu-22.04

variables:
- group: NetlifySecrets
- group: BuildSecrets 
- name: buildFolder
  value: dist

steps:
- script: echo "👋 Hello from the pipeline!"
  displayName: 'Say Hello'

# Install dependencies
- script: npm install
  displayName: 'Install dependencies'

# Optional: Relax TypeScript strict rules
- script: |
    echo "🔧 Relaxing TS rules"
    for file in tsconfig.json tsconfig.app.json tsconfig.node.json; do
      if [ -f "$file" ]; then
        echo "Patching $file"
        sed -i 's/"noUnusedLocals": true/"noUnusedLocals": false/g' "$file" || true
        sed -i 's/"noUnusedParameters": true/"noUnusedParameters": false/g' "$file" || true
        grep -q '"noUnusedLocals"' "$file" || sed -i '/"compilerOptions": {/a \    "noUnusedLocals": false,' "$file"
        grep -q '"noUnusedParameters"' "$file" || sed -i '/"compilerOptions": {/a \    "noUnusedParameters": false,' "$file"
      fi
    done
  displayName: 'Relax TypeScript rules'

# Build project (injecting Supabase env vars)
- script: |
    echo "🔨 Building with Supabase env..."
    tsc -b || echo "⚠️ Skipping TS errors"
    vite build
  displayName: '🛠️ Build project'
  env:
    VITE_SUPABASE_URL: $(VITE_SUPABASE_URL)
    VITE_SUPABASE_ANON_KEY: $(VITE_SUPABASE_ANON_KEY)

# Optional: Confirm dist folder exists
- script: ls -la $(buildFolder)
  displayName: '📦 Check dist folder contents'

# Deploy to Netlify
- script: |
    npm install -g netlify-cli
    echo "🚀 Deploying to Netlify..."
    netlify deploy --prod --dir=$(buildFolder) --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID
  displayName: '🚀 Deploy to Netlify'
  env:
    NETLIFY_AUTH_TOKEN: $(NETLIFY_AUTH_TOKEN)
    NETLIFY_SITE_ID: $(NETLIFY_SITE_ID)
