trigger:
  branches:
    include:
      - main
      - dev

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install dependencies'

  - script: |
      npm run build
    displayName: 'Build app with Vite'

  - script: |
      npm install -g netlify-cli
      netlify deploy --dir=dist --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN --prod
    env:
      NETLIFY_SITE_ID: $(NETLIFY_SITE_ID)
      NETLIFY_AUTH_TOKEN: $(NETLIFY_AUTH_TOKEN)
    displayName: 'Deploy to Netlify'
