# Starter pipeline
# Build and deploy your project to Netlify from Azure DevOps
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-22.04

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# Install dependencies
- script: npm install
  displayName: 'Install dependencies'

# Patch tsconfig.json to allow unused variables (prevents build failure)
- script: |
    echo "Patching tsconfig.json..."
    jq '.compilerOptions.noUnusedLocals = false | .compilerOptions.noUnusedParameters = false' tsconfig.json > tsconfig-patched.json
    mv tsconfig-patched.json tsconfig.json
  displayName: 'Relax TypeScript strictness (temp fix)'
  condition: succeeded()

# Build your project
- script: npm run build
  displayName: 'Build project'

# Deploy to Netlify
- script: |
    npm install -g netlify-cli
    netlify deploy --dir=dist --prod --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID
  displayName: 'Deploy to Netlify'
  env:
    NETLIFY_AUTH_TOKEN: $(NETLIFY_AUTH_TOKEN)
    NETLIFY_SITE_ID: $(NETLIFY_SITE_ID)
