# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-22.04

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# Install dependencies
- script: npm install
  displayName: 'Install dependencies'

# Build your project (assuming your build output goes to `dist/`)
- script: npm run build
  displayName: 'Build project'

# Deploy to Netlify
- script: |
    npm install -g netlify-cli
    netlify deploy --dir=dist --prod --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID
  displayName: 'Deploy to Netlify'
  env:
    NETLIFY_AUTH_TOKEN: $(NETLIFY_AUTH_TOKEN)
    NETLIFY_SITE_ID: $(NETLIFY_SITE_ID)
