# Azure DevOps pipeline for building and deploying to Netlify (college project vibes)
trigger:
- main

pool:
  vmImage: ubuntu-22.04

steps:
# Just saying hi
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# Install dependencies
- script: npm install
  displayName: 'Install dependencies'

# Relax TypeScript rules (for all tsconfig*.json files)
- script: |
    echo "Relaxing TypeScript rules in all tsconfig*.json files..."
    for file in $(find . -name "tsconfig*.json"); do
      echo "Patching $file"
      node -e "let fs=require('fs');let f='$file';let j=JSON.parse(fs.readFileSync(f));j.compilerOptions=j.compilerOptions||{};j.compilerOptions.noUnusedLocals=false;j.compilerOptions.noUnusedParameters=false;fs.writeFileSync(f,JSON.stringify(j,null,2));"
    done
  displayName: 'Relax TypeScript rules globally'

# Build the project
- script: npm run build
  displayName: 'Build project'

# Deploy to Netlify
- script: |
    npm install -g netlify-cli
    netlify deploy --dir=dist --prod --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID
  displayName: 'Deploy to Netlify'
  env:
    NETLIFY_AUTH_TOKEN: $(NETLIFY_AUTH_TOKEN)
    NETLIFY_SITE_ID: $(NETLIFY_SITE_ID)
