trigger:
- main

pool:
  vmImage: ubuntu-22.04

steps:
- script: echo Hello, pipeline!
  displayName: 'Say hello'

# Install dependencies
- script: npm install
  displayName: 'Install dependencies'

# Disable strict TypeScript rules (noUnusedLocals, noUnusedParameters)
- script: |
    echo "Disabling strict TS rules (sed edition)"
    for file in tsconfig.json tsconfig.app.json tsconfig.node.json; do
      if [ -f "$file" ]; then
        echo "Patching $file"
        sed -i 's/"noUnusedLocals": true/"noUnusedLocals": false/g' "$file"
        sed -i 's/"noUnusedParameters": true/"noUnusedParameters": false/g' "$file"
        grep -q '"noUnusedLocals"' "$file" || sed -i '/"compilerOptions": {/a \    "noUnusedLocals": false,' "$file"
        grep -q '"noUnusedParameters"' "$file" || sed -i '/"compilerOptions": {/a \    "noUnusedParameters": false,' "$file"
      fi
    done
  displayName: 'Relax TypeScript rules (sed edition)'

# Build the project
- script: npm run build
  displayName: 'Build project'

# Deploy to Netlify
- script: |
    npm install -g netlify-cli
    netlify deploy --dir=dist --prod --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID
  displayName: 'Deploy to Netlify'
  env:
    NETLIFY_AUTH_TOKEN: $(NETLIFY_AUTH_TOKEN)
    NETLIFY_SITE_ID: $(NETLIFY_SITE_ID)
