trigger:
  branches:
    include:
      - dev
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install dependencies'

  - script: |
      npm run build
    displayName: 'Build app with Vite'

  - script: |
      npm install -g netlify-cli
      netlify deploy --prod --dir=dist --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN
    env:
      NETLIFY_AUTH_TOKEN: $(NETLIFY_AUTH_TOKEN)
      NETLIFY_SITE_ID: $(NETLIFY_SITE_ID)
    displayName: 'Deploy to Netlify'
